export default {
  setUrl: 'setUrl',
  sendRequest: 'sendRequest',
  receiveResponse: 'receiveResponse',
  selectAuthType: 'selectAuthType',
  setAuthParams: 'setAuthParams',
  requestSent: 'requestSent',
  selectHttpMethod: 'selectHttpMethod',
  setRequestBody: 'setRequestBody',
  selectContentType: 'selectContentType',
  setRequestHeaders: 'setRequestHeaders',
  resetState: 'resetState',
  setState: 'setState',
  nextState: 'nextState',
  previousState: 'previousState',
  indicateBackendError: 'indicateBackendError',
  clearErrors: 'clearErrors',
  cancelRequest: 'cancelRequest',
  requestCancelled: 'requestCancelled',
  validateForms: 'validateForms'
};
