export default {
  setUrl: 'setUrl',
  sendRequest: 'sendRequest',
  receiveResponse: 'receiveResponse',
  selectAuthType: 'selectAuthType',
  setAuthParams: 'setAuthParams',
  requestSent: 'requestSent',
  selectHttpMethod: 'selectHttpMethod',
  setRequestBody: 'setRequestBody',
  selectContentType: 'selectContentType',
  setRequestHeaders: 'setRequestHeaders',
  resetState: 'resetState',
  indicateBackendError: 'indicateBackendError',
  clearErrors: 'clearErrors',
  cancelRequest: 'cancelRequest',
  requestCancelled: 'requestCancelled',
  validateForms: 'validateForms',
  saveToFile: 'saveToFile',
  fileSaveResult: 'fileSaveResult',
  clearInfoMessage: 'clearInfoMessage'
};
