export default {
  UPDATE_URL: 'UPDATE_URL',
  UPDATE_RESPONSE: 'UPDATE_RESPONSE',
  SELECT_AUTH_TYPE: 'SELECT_AUTH_TYPE',
  SET_AUTH_PARAMS: 'SET_AUTH_PARAMS',
  UPDATE_SENT_HEADERS: 'UPDATE_SENT_HEADERS',
  UPDATE_NETWORK_STATUS: 'UPDATE_NETWORK_STATUS',
  SET_SENT_REQUEST_HEADERS: 'SET_SENT_REQUEST_HEADERS',
  SELECT_HTTP_METHOD: 'SELECT_HTTP_METHOD',
  SET_REQUEST_BODY: 'SET_REQUEST_BODY'
};
