export default {
  UPDATE_URL: 'UPDATE_URL',
  UPDATE_RESPONSE: 'UPDATE_RESPONSE',
  SELECT_AUTH_TYPE: 'SELECT_AUTH_TYPE',
  SET_AUTH_PARAMS: 'SET_AUTH_PARAMS',
  UPDATE_REQUEST_HEADERS: 'UPDATE_REQUEST_HEADERS'
};
